package af.uiswing.ui.panels;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author Alessandro Falappa <alex.falappa@gmail.com>
 */
public class AdvancedSearchPanel extends javax.swing.JPanel {

    private DefaultListModel dlmSearchParams = new DefaultListModel();
    private DefaultComboBoxModel dcbmOpsStrings = new DefaultComboBoxModel();
    private DefaultComboBoxModel dcbmOpsNumbers = new DefaultComboBoxModel();
    private DefaultComboBoxModel dcbmOpsDates = new DefaultComboBoxModel();

    /**
     * Creates new form AdvancedSearchPanel
     */
    public AdvancedSearchPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbField = new javax.swing.JComboBox();
        cbOp = new javax.swing.JComboBox();
        ftxValue = new javax.swing.JFormattedTextField();
        bRemove = new javax.swing.JButton();
        bAdd = new javax.swing.JButton();
        scroller = new javax.swing.JScrollPane();
        lExpressions = new javax.swing.JList();

        cbField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Title", "Subtitle", "Publisher", "Series", "Issue", "Drawings by", "Texts by", "Cover by" }));

        cbOp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", ">", ">=", "<", "<=", "contains", " " }));

        ftxValue.setColumns(10);

        bRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/af/uiswing/ui/images_16x16/glyphicons_433_minus.png"))); // NOI18N
        bRemove.setEnabled(false);

        bAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/af/uiswing/ui/images_16x16/glyphicons_432_plus.png"))); // NOI18N

        lExpressions.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Title contains 'Orfani'", "Issue >= 10" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lExpressions.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lExpressions.setVisibleRowCount(4);
        lExpressions.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lExpressionsValueChanged(evt);
            }
        });
        scroller.setViewportView(lExpressions);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroller)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bRemove)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ftxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bRemove)
                        .addComponent(bAdd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroller)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lExpressionsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lExpressionsValueChanged
        bRemove.setEnabled(lExpressions.getSelectedIndex() >= 0);
    }//GEN-LAST:event_lExpressionsValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bRemove;
    private javax.swing.JComboBox cbField;
    private javax.swing.JComboBox cbOp;
    private javax.swing.JFormattedTextField ftxValue;
    private javax.swing.JList lExpressions;
    private javax.swing.JScrollPane scroller;
    // End of variables declaration//GEN-END:variables
}
