package af.uiswing.ui;

import af.uiswing.ui.dialogs.NewComicDialog;

/**
 * Comicat Swing UI main frame.
 *
 * @author Alessandro Falappa <alex.falappa@gmail.com>
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bSearch = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        scroller = new javax.swing.JScrollPane();
        tbResults = new javax.swing.JTable();
        pSearch = new javax.swing.JPanel();
        aspParams = new af.uiswing.ui.panels.AdvancedSearchPanel();
        sspParams = new af.uiswing.ui.panels.SimpleSearchPanel();
        mbMenu = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miNew = new javax.swing.JMenuItem();
        sep1 = new javax.swing.JPopupMenu.Separator();
        mImport = new javax.swing.JMenu();
        mExport = new javax.swing.JMenu();
        sep2 = new javax.swing.JPopupMenu.Separator();
        miExit = new javax.swing.JMenuItem();
        mEdit = new javax.swing.JMenu();
        miSettings = new javax.swing.JMenuItem();
        mHelp = new javax.swing.JMenu();
        miAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comicat");
        setPreferredSize(new java.awt.Dimension(600, 400));

        bSearch.setFont(bSearch.getFont().deriveFont(bSearch.getFont().getStyle() | java.awt.Font.BOLD));
        bSearch.setText("Search");

        bClear.setText("Clear");

        tbResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroller.setViewportView(tbResults);

        pSearch.setLayout(new java.awt.CardLayout());
        pSearch.add(aspParams, "advanced");
        pSearch.add(sspParams, "simple");

        mFile.setText("File");

        miNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        miNew.setText("New Comic");
        miNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNewActionPerformed(evt);
            }
        });
        mFile.add(miNew);
        mFile.add(sep1);

        mImport.setText("Import");
        mImport.setEnabled(false);
        mFile.add(mImport);

        mExport.setText("Export");
        mExport.setEnabled(false);
        mFile.add(mExport);
        mFile.add(sep2);

        miExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        mFile.add(miExit);

        mbMenu.add(mFile);

        mEdit.setText("Edit");

        miSettings.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        miSettings.setText("Settings");
        mEdit.add(miSettings);

        mbMenu.add(mEdit);

        mHelp.setText("Help");

        miAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        miAbout.setText("About");
        mHelp.add(miAbout);

        mbMenu.add(mHelp);

        setJMenuBar(mbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroller)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSearch)
                            .addComponent(bClear))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bClear, bSearch});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bSearch))
                    .addComponent(pSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroller)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        dispose();
    }//GEN-LAST:event_miExitActionPerformed

    private void miNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNewActionPerformed
        NewComicDialog ncd = new NewComicDialog(this);
        ncd.setLocationRelativeTo(this);
        ncd.setVisible(true);
    }//GEN-LAST:event_miNewActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private af.uiswing.ui.panels.AdvancedSearchPanel aspParams;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bSearch;
    private javax.swing.JMenu mEdit;
    private javax.swing.JMenu mExport;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mHelp;
    private javax.swing.JMenu mImport;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miNew;
    private javax.swing.JMenuItem miSettings;
    private javax.swing.JPanel pSearch;
    private javax.swing.JScrollPane scroller;
    private javax.swing.JPopupMenu.Separator sep1;
    private javax.swing.JPopupMenu.Separator sep2;
    private af.uiswing.ui.panels.SimpleSearchPanel sspParams;
    private javax.swing.JTable tbResults;
    // End of variables declaration//GEN-END:variables
}
